language: java
jdk:
  - oraclejdk8
before_install:
  - mkdir 3rdparty
  - cd 3rdparty
  - mkdir feedzilla
  - cd feedzilla
  - git clone https://github.com/sidorovis/feedzilla-java.git ./
  - mvn install
  - cd ../../


